### ISSUE TITLE
Add support for OUI list

### ISSUE THREAD

**Issue by rnazmo** [rnazmo/mag#10]
In GitLab by @rnazmo on Jan 17, 2021, 12:30

## TODO

- [x] http://standards-oui.ieee.org/oui/oui.csv にアクセスし, リストを取得するスクリプトを作る(これを oui-list.csv とする)
      -> これは shell script として書く?
- [x] 開発のためのダミー用データ example.csv を作る(実データだと大きすぎて手元で扱いづらいので)
- [x] oui-list.csv をパースして構造体に落とし込むコードを書く
- [x] ↑と並行して構造体・データ構造を具体的に考える
- [x] promptui に組み込んでみる(小さなサンプルコード作って試す)
- [x] interactive のどこに組み込むか考える
  ```
  ...
  A. "Specify OUI?"
    1. "Type specific OUI" -> go to B
    2. "Choose from list"  -> go to C
    3. "No"                -> go to D
  B. "Type specific OUI."
    -> Type the OUI & go to D
  C. "Choose from list."
    TODO:
      - リストを一覧で表示する. 並べる順序やソートはとりあえず考えなくてよい.
      - interactive search でリストを絞り込める.
      - row を一つ選んで Enter を押すことで次へ進む.
  D. Select format
  ...

## Notes
### リストを取得するスクリプトはどこにどう書く？
とりあえず Makefile に直接書いた.
現在ではたった一行のスクリプトなのでこれが一番簡潔.
そのうちスクリプトの内容が数行に増えたら別ファイルに分けるかも？

### リストを絞り込むための検索ボックスはどう実装する？
promptui で用意されている. Select.Searcher を使えば良い.
#### ref
- https://godoc.org/github.com/manifoldco/promptui#Select
- https://github.com/manifoldco/promptui/blob/981a3cab68f6f3481bf42c6a98521af7fbd14fae/_examples/custom_select/main.go

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 23, 2021, 16:58

marked the task **http://standards-oui.ieee.org/oui/oui.csv にアクセスし, リストを取得するスクリプトを作る(これを oui-list.csv とする)** as completed

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 23, 2021, 16:58

marked the task **開発のためのダミー用データ dummy-list.csv を作る(実データだと大きすぎて手元で扱いづらいので)** as completed

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 23, 2021, 16:58

changed the description

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 23, 2021, 17:45

changed the description

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 25, 2021, 12:18

marked the task **interactive のどこに組み込むか考える** as completed

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 25, 2021, 13:47

changed the description

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 25, 2021, 14:01

changed the description

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 25, 2021, 16:54

marked the task **oui-list.csv をパースして構造体に落とし込むコードを書く** as completed

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 25, 2021, 16:54

marked the task **↑と並行して構造体・データ構造を具体的に考える** as completed

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 25, 2021, 16:54

marked the task **promptui に組み込んでみる(小さなサンプルコード作って試す)** as completed

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 25, 2021, 17:12

mentioned in merge request !3

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 25, 2021, 17:12

mentioned in commit 756baafb465d6bb5922ec08d0b3514c343235509

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jan 25, 2021, 17:14

done
