### ISSUE TITLE
Migrate the repo from GitLab to GitHub

### ISSUE THREAD

**Issue by rnazmo** [rnazmo/mag#17]
In GitLab by @rnazmo on May 9, 2021, 16:28

## TODO

- [x] Migrate the repo from GitLab to GitHub (with https://github.com/piceaTech/node-gitlab-2-github)
- [x] Update `go.mod`
- [x] Migrate the CI: gitlab-ci -> github actions

**Comment by rnazmo** [comment]
In GitLab by @rnazmo on Jun 21, 2021, 18:25

changed the description
